const studentDatabase = [

    // Data from ResultsSummary_YLE_Starters_02_OCTOBER_2023.pdf
    { lastName: "LÓPEZ REY", firstName: "MAURICIO", exam: "YLE Starters", year: "2023", score: "RW2-L4-S2" },

// Data from ResultsSummary_YLE_Starters_30_AUGUST_2023.pdf
    { lastName: "BONILLA URUEÑA", firstName: "DAVID ANDRÉS", exam: "YLE Starters", year: "2023", score: "RW1-L5-S5" }, 
    { lastName: "GARCÍA GUTIÉRREZ", firstName: "FELIPE", exam: "YLE Starters", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "LÓPEZ LÓPEZ", firstName: "LUIS SANTIAGO", exam: "YLE Starters", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "GONZALEZ CANTOR", firstName: "SAMUEL", exam: "YLE Starters", year: "2023", score: "RW1-L4-S5" }, 
    { lastName: "RINCON MARIÑO", firstName: "RAFAELLA", exam: "YLE Starters", year: "2023", score: "RW2-L5-S5" }, 
    { lastName: "SORDELLA JAIME", firstName: "MATEO", exam: "YLE Starters", year: "2023", score: "RW3-L4-S5" }, 
    { lastName: "PEREIRA ARIZA", firstName: "JOEL SANTIAGO", exam: "YLE Starters", year: "2023", score: "RW1-L4-S5" }, 
    { lastName: "PINZÓN GONZÁLEZ", firstName: "DANNA", exam: "YLE Starters", year: "2023", score: "RW1-L5-S5" }, 
    { lastName: "CASTELBLANCO ROMERO", firstName: "EVELYN", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "ORTIZ NIÑO", firstName: "HANNA", exam: "YLE Starters", year: "2023", score: "RW2-L4-S4" }, 
    { lastName: "CAICEDO BENAVIDES", firstName: "JOAQUÍN", exam: "YLE Starters", year: "2023", score: "RW2-L5-S4" }, 
    { lastName: "CASTILLO MONROY", firstName: "JUAN ANDRÉS", exam: "YLE Starters", year: "2023", score: "RW2-L5-S5" }, 
    { lastName: "ALTAHONA BUITRAGO", firstName: "JUAN JOSÉ", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "MONDRAGÓN TORRES", firstName: "JUAN JOSÉ", exam: "YLE Starters", year: "2023", score: "RW1-L3-S4" }, 
    { lastName: "CAICEDO NÁRVAEZ", firstName: "JUAN MARTÍN", exam: "YLE Starters", year: "2023", score: "RW3-L3-S5" }, 
    { lastName: "GARCÍA ESCOBAR", firstName: "MARIANA", exam: "YLE Starters", year: "2023", score: "RW2-L4-S4" }, 
    { lastName: "DUQUE RODRIGUEZ", firstName: "MARTIN EMILIO", exam: "YLE Starters", year: "2023", score: "RW1-L1-S3" }, 
    { lastName: "FORIGUA BARRERA", firstName: "SANTIAGO EDUARDO", exam: "YLE Starters", year: "2023", score: "RW1-L3-S5" }, 
    { lastName: "ESCOBAR GOYES", firstName: "VALENTINA", exam: "YLE Starters", year: "2023", score: "RW1-L4-S5" }, 
    { lastName: "PINZÓN FONSECA", firstName: "VALENTINA", exam: "YLE Starters", year: "2023", score: "RW3-L5-S4" }, 
    { lastName: "GUTIÉRREZ LUIS", firstName: "ANDRÉS CAMILO", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "CORONADO JIMÉNEZ", firstName: "ANDRÉS FELIPE", exam: "YLE Starters", year: "2023", score: "RW2-L3-S2" }, 
    { lastName: "AGUILERA MORENO", firstName: "GABRIELA", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "ROJAS FLÓREZ", firstName: "ISABELLA", exam: "YLE Starters", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "BLANCO LÓPEZ", firstName: "KATIA MARCELA", exam: "YLE Starters", year: "2023", score: "RW1-L4-S4" }, 
    { lastName: "MALDONADO BEDOYA", firstName: "MARIANA", exam: "YLE Starters", year: "2023", score: "RW1-L3-S3" }, 
    { lastName: "GONZÁLEZ HOYOS", firstName: "MARTÍN", exam: "YLE Starters", year: "2023", score: "Pending" }, 
    { lastName: "JARA LOZANO", firstName: "VALERIE", exam: "YLE Starters", year: "2023", score: "RW1-L4-S4" }, 
    { lastName: "ALMANZA MURCIA", firstName: "GABRIELA", exam: "YLE Starters", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "CÁRDENAS ROMERO", firstName: "SANTIAGO", exam: "YLE Starters", year: "2023", score: "RW1-L4-S5" }, 
    { lastName: "CORONADO LÓPEZ", firstName: "JACOBO", exam: "YLE Starters", year: "2023", score: "RW1-L2-S3" }, 
    { lastName: "DÍAZ GÓMEZ", firstName: "SAMUEL", exam: "YLE Starters", year: "2023", score: "RW2-L5-S4" }, 
    { lastName: "LÓPEZ REY", firstName: "MAURICIO", exam: "YLE Starters", year: "2023", score: "Pending" }, 
    { lastName: "MACIAS PERICO", firstName: "LUCIANA", exam: "YLE Starters", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "MONTERO PERDOMO", firstName: "MARTINA", exam: "YLE Starters", year: "2023", score: "RW2-L4-S4" }, 
    { lastName: "MONTILLA SIERRA", firstName: "SEBASTIÁN MAURICIO", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "MORALES FERIA", firstName: "MARTINA", exam: "YLE Starters", year: "2023", score: "RW3-L5-S3" }, 
    { lastName: "MUNEVAR DUITAMA", firstName: "JULIETA", exam: "YLE Starters", year: "2023", score: "RW2-L3-S5" }, 
    { lastName: "TORRALBA ROJAS", firstName: "AURA LUCÍA", exam: "YLE Starters", year: "2023", score: "RW2-L3-S5" }, 
    { lastName: "VALENCIA LOZANO", firstName: "SOFÍA", exam: "YLE Starters", year: "2023", score: "RW3-L4-S4" }, 
    { lastName: "MUÑOZ CORREA", firstName: "VIOLETTA", exam: "YLE Starters", year: "2023", score: "RW2-L4-S4" }, 
    { lastName: "FONTALVO SALAS", firstName: "DANIELA", exam: "YLE Starters", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "FONTALVO SALAS", firstName: "JUAN FELIPE", exam: "YLE Starters", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "LOAIZA PINTO", firstName: "IAN SANTIAGO", exam: "YLE Starters", year: "2023", score: "RW4-L5-S5" }, 

    // Data from ResultsSummary_YLE_Starters_14_AUGUST_2024.pdf
    { lastName: "ABOUZELOF FORERO", firstName: "AMIRA", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "AGUIRRE REY", firstName: "ALVARO SAMUEL", exam: "YLE Starters", year: "2024", score: "RW1-L3-S4" }, 
    { lastName: "APONTE BAUTE", firstName: "VERÓNICA", exam: "YLE Starters", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "BUITRAGO RATIVA", firstName: "MIGUEL ÁNGEL", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "CADENA CAMARGO", firstName: "AMBER ELAINE", exam: "YLE Starters", year: "2024", score: "RW2-L5-S5" }, 
    { lastName: "CASTAÑEDA LEÓN", firstName: "ANDRÉS FELIPE", exam: "YLE Starters", year: "2024", score: "RW1-L3-S4" }, 
    { lastName: "CASTRO RODRIGUEZ", firstName: "VALERIA", exam: "YLE Starters", year: "2024", score: "RW1-L2-S5" }, 
    { lastName: "CORAL AVILA", firstName: "RAFAEL EMILIO", exam: "YLE Starters", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "HENAO MORA", firstName: "JUAN SANTIAGO", exam: "YLE Starters", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "MURCIA BARRERA", firstName: "SANTIAGO", exam: "YLE Starters", year: "2024", score: "RW1-L1-S4" }, 
    { lastName: "NOCETTI RINCON", firstName: "MARTIN YOSSHUAH", exam: "YLE Starters", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "PINEDA DIAZ", firstName: "JUAN FELIPE", exam: "YLE Starters", year: "2024", score: "RW4-L3-S5" }, 
    { lastName: "PINTO LIZARAZO", firstName: "VALERIA", exam: "YLE Starters", year: "2024", score: "RW1-L4-S5" }, 
    { lastName: "QUINTERO QUIROZ", firstName: "SALVADOR", exam: "YLE Starters", year: "2024", score: "RW5-L3-S4" }, 
    { lastName: "RAMOS LOPEZ", firstName: "JOSE EMILIANO", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "REY ALZATE", firstName: "MARÍA ALEJANDRA", exam: "YLE Starters", year: "2024", score: "RW2-L4-S4" }, 
    { lastName: "RODRIGUEZ CAICEDO", firstName: "ISABELLA", exam: "YLE Starters", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "RODRÍGUEZ CASTRO", firstName: "JUAN DIEGO", exam: "YLE Starters", year: "2024", score: "RW2-L3-S5" }, 
    { lastName: "RUBIO FORERO", firstName: "ANA SOFIA", exam: "YLE Starters", year: "2024", score: "RW1-L3-S3" }, 
    { lastName: "TORRES LIMA", firstName: "THIAGO ALONSO", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "TORRES SANCHEZ", firstName: "MATIAS", exam: "YLE Starters", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "ALFONSO GORDILLO", firstName: "EMILIANO", exam: "YLE Starters", year: "2024", score: "RW1-L3-S3" }, 
    { lastName: "ARDILA HERRERA", firstName: "GUADALUPE", exam: "YLE Starters", year: "2024", score: "RW1-L4-S5" }, 
    { lastName: "BERMÚDEZ SANABRIA", firstName: "MARÍA ELENA", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "BOTÓN PABÓN", firstName: "DANIEL ESTEBAN", exam: "YLE Starters", year: "2024", score: "RW2-L3-S3" }, 
    { lastName: "CASTRO COHECHA", firstName: "JUAN ESTEBAN", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "DÍAZ GARZÓN", firstName: "JERONIMO", exam: "YLE Starters", year: "2024", score: "RW1-L1-S3" }, 
    { lastName: "GALVIS FLORIÁN", firstName: "DAVID", exam: "YLE Starters", year: "2024", score: "RW3-L2-S3" }, 
    { lastName: "GARCÍA FRESNEDA", firstName: "SAMUEL ALEJANDRO", exam: "YLE Starters", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "GOMEZCASERES ARIAS", firstName: "LUIS SANTIAGO", exam: "YLE Starters", year: "2024", score: "RW3-L3-S4" }, 
    { lastName: "LANCHEROS ANGEL", firstName: "JUAN DIEGO", exam: "YLE Starters", year: "2024", score: "RW2-L4-S4" }, 
    { lastName: "LÓPEZ CORTÉS", firstName: "ESTEBAN", exam: "YLE Starters", year: "2024", score: "RW1-L2-S5" }, 
    { lastName: "MARTINEZ MONGUI", firstName: "JULIETA", exam: "YLE Starters", year: "2024", score: "RW3-L4-S4" }, 
    { lastName: "MORALES FERIA", firstName: "VICTORIA", exam: "YLE Starters", year: "2024", score: "RW2-L4-S3" }, 
    { lastName: "PEINADO CRUZ", firstName: "EMMANUEL", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "PINILLA SANTAMARIA", firstName: "ISABELLA", exam: "YLE Starters", year: "2024", score: "RW3-L5-S3" }, 
    { lastName: "PISCAL TERÁN", firstName: "JULIETA", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "QUINTANA CAMACHO", firstName: "DANIELA ALEJANDRA", exam: "YLE Starters", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "QUINTERO PLAZAS", firstName: "FRANCISCO", exam: "YLE Starters", year: "2024", score: "RW3-L5-S3" }, 
    { lastName: "ROJAS VILLAMIZAR", firstName: "MATÍAS", exam: "YLE Starters", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "SANCHEZ GIL", firstName: "GABRIELA", exam: "YLE Starters", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "SANCHEZ GONZÁLEZ", firstName: "SARA VICTORIA", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "ARIAS CORONEL", firstName: "SAMUEL", exam: "YLE Starters", year: "2024", score: "RW3-L3-S5" }, 
    { lastName: "BAYONA BAYONA", firstName: "JUAN ESTEBAN", exam: "YLE Starters", year: "2024", score: "RW1-L1-S2" }, 
    { lastName: "CAICEDO NARVAEZ", firstName: "JOSE PABLO", exam: "YLE Starters", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CELEITA ANGARITA", firstName: "DANNA VICTORIA", exam: "YLE Starters", year: "2024", score: "RW5-L5-S4" }, 
    { lastName: "CUADRADO SAMBONI", firstName: "MATILDE ELENA", exam: "YLE Starters", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CUEVAS MURILLO", firstName: "SALVADOR", exam: "YLE Starters", year: "2024", score: "RW1-L2-S5" }, 
    { lastName: "DUARTE VEGA", firstName: "SARA VALENTINA", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "FUENTES MAYORGA", firstName: "LUNA VALENTINA", exam: "YLE Starters", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "GALLEGO LIZARAZO", firstName: "CARLOS ANDRES", exam: "YLE Starters", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "GALVIS RUBIO", firstName: "SALOMÉ", exam: "YLE Starters", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "GARZON ESGUERRA", firstName: "ANTHONY", exam: "YLE Starters", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "GOMEZ ESCOBAR", firstName: "JUAN DIEGO", exam: "YLE Starters", year: "2024", score: "RW2-L3-S5" }, 
    { lastName: "GÓMEZ REINOSO", firstName: "PABLO ANTONIO", exam: "YLE Starters", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "GONZÁLEZ VELASCO", firstName: "DANIEL FELIPE", exam: "YLE Starters", year: "2024", score: "RW1-L4-S3" }, 
    { lastName: "HERNÁNDEZ ORTEGA", firstName: "JERÓNIMO", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "JARA LÓPEZ", firstName: "MATIAS", exam: "YLE Starters", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "MÉNDEZ ARIZA", firstName: "LINA JULIANA", exam: "YLE Starters", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "ORDOÑEZ VALENCIA", firstName: "JULIÁN RICARDO", exam: "YLE Starters", year: "2024", score: "RW1-L2-S5" }, 
    { lastName: "ORTIZ GONZÁLEZ", firstName: "CELESTE", exam: "YLE Starters", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "VARGAS ESPITIA", firstName: "JUAN JOSE", exam: "YLE Starters", year: "2024", score: "RW1-L1-S3" }, 

    // Data from ResultsSummary_YLE_Starters_02_SEPTEMBER_2025.pdf
    { lastName: "Cardenas Serrano", firstName: "Ana Sofia", exam: "YLE Starters", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "Carreño Tobar", firstName: "Christopher", exam: "YLE Starters", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "Flórez González", firstName: "Sara Isabella", exam: "YLE Starters", year: "2025", score: "RW1-L2-S4" }, 
    { lastName: "Gamba Solano", firstName: "Samuel Andrés", exam: "YLE Starters", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "García González", firstName: "Alma", exam: "YLE Starters", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "Joya Osuna", firstName: "Thiago", exam: "YLE Starters", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "Lozano Guaqueta", firstName: "Juan Fernando", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Malpica Mahecha", firstName: "Juan Felipe", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Martínez Mongui", firstName: "Violeta", exam: "YLE Starters", year: "2025", score: "RW2-L3-S4" }, 
    { lastName: "Quintero Arenas", firstName: "María Angélica", exam: "YLE Starters", year: "2025", score: "RW1-L3-S5" }, 
    { lastName: "Rodríguez Giraldo", firstName: "Juan Felipe", exam: "YLE Starters", year: "2025", score: "RW2-L3-S4" }, 
    { lastName: "Rojas Florez", firstName: "Matias", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Rojas Tovar", firstName: "Julieta", exam: "YLE Starters", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "Soacha Mantilla", firstName: "Gabriel Antonio", exam: "YLE Starters", year: "2025", score: "RW2-L3-S4" }, 
    { lastName: "Virviescas Chaux", firstName: "Gabriel", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Alvis Ortíz", firstName: "Samuel Esteban", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Aragon Ayala", firstName: "Santiago", exam: "YLE Starters", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "Avella Pinzon", firstName: "Ethan", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Castañeda Leon", firstName: "Maria Juliana", exam: "YLE Starters", year: "2025", score: "RW2-L2-S4" }, 
    { lastName: "Castro Caleño", firstName: "Danna Valentina", exam: "YLE Starters", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "Franco Muñoz", firstName: "Leah Violet", exam: "YLE Starters", year: "2025", score: "RW2-L2-S5" }, 
    { lastName: "Garcia Nuñez", firstName: "Juan Guillermo", exam: "YLE Starters", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "Guerrero Flechas", firstName: "Miranda", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Gutiérrez Esquivel", firstName: "María Lucia", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Jara Lozano", firstName: "Lia Thaliana", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Martínez Guachetá", firstName: "Gabriel Felipe", exam: "YLE Starters", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "Morales Buitrago", firstName: "Santiago", exam: "YLE Starters", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "Murcia Rodríguez", firstName: "Martin", exam: "YLE Starters", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "Poveda navarro", firstName: "Guadalupe", exam: "YLE Starters", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "Serrano Rodríguez", firstName: "Juana Valentina", exam: "YLE Starters", year: "2025", score: "RW1-L2-S5" }, 
    { lastName: "Soriano Devia", firstName: "Isabella", exam: "YLE Starters", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "Ticona Astete", firstName: "Lucas Octavio", exam: "YLE Starters", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "Almanza Murcia", firstName: "Juan Martín", exam: "YLE Starters", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "Andrade Cruz", firstName: "Victoria", exam: "YLE Starters", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "Arias Prieto", firstName: "Amanda", exam: "YLE Starters", year: "2025", score: "RW2-L3-S4" }, 
    { lastName: "Avella Villasmil", firstName: "Emmanuel", exam: "YLE Starters", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "Blanco López", firstName: "Angel Mateo", exam: "YLE Starters", year: "2025", score: "RW1-L3-S4" }, 
    { lastName: "Camargo Silva", firstName: "Alejandra", exam: "YLE Starters", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "David Ferrucho", firstName: "Maria Isabella", exam: "YLE Starters", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "García Urueña", firstName: "Gabriela", exam: "YLE Starters", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "Higuera López", firstName: "Santiago Andrés", exam: "YLE Starters", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "Huelvas Pertuz", firstName: "Manuela Celeste", exam: "YLE Starters", year: "2025", score: "RW4-L5-S4" }, 
    { lastName: "Ibañez Marin", firstName: "Anwar Said", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Loboguerrero Ulloa", firstName: "Daniel Andrés", exam: "YLE Starters", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "López Bahamon", firstName: "Emilia", exam: "YLE Starters", year: "2025", score: "RW2-L1-S4" }, 
    { lastName: "MartínezPérez", firstName: "Emilio esteban", exam: "YLE Starters", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "Niño Rodríguez", firstName: "Santiago", exam: "YLE Starters", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "Romero González", firstName: "Nichol Valeria", exam: "YLE Starters", year: "2025", score: "RW2-L5-S5" }, 
    { lastName: "Useche Reyes", firstName: "Maria Alejandra", exam: "YLE Starters", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "Coley López", firstName: "Renata Isabel", exam: "YLE Starters", year: "2025", score: "RW1-L2-S5" }, 
    { lastName: "Osses Matsumi", firstName: "Aiki", exam: "YLE Starters", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "Aguilar Castillo", firstName: "Juan Camilo", exam: "YLE Starters", year: "2025", score: "RW1-L2-S5" }, 
    { lastName: "Zapata Rico", firstName: "Benjamin", exam: "YLE Starters", year: "2025", score: "RW3-L4-S4" }, 
    { lastName: "Gómez López", firstName: "Martina", exam: "YLE Starters", year: "2025", score: "RW1-L1-S2" }, 
    { lastName: "Puyo González", firstName: "Maria Antonia", exam: "YLE Starters", year: "2025", score: "RW2-L4-S4" }, 

    
    

     // Data from ResultsSummary_YLE_Movers_05_OCTOBER_2021.pdf
    { lastName: "Parra Galeano", firstName: "Sara Lucía", exam: "YLE Movers", year: "2021", score: "RW1-L4-S2" }, 
    { lastName: "Pinilla Blandón", firstName: "Marianna", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Piscal Terán", firstName: "Isabella", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Sánchez Romero", firstName: "María Fernanda", exam: "YLE Movers", year: "2021", score: "RW2-L4-S4" }, 
    { lastName: "Tamayo Chaparro", firstName: "Gabriel", exam: "YLE Movers", year: "2021", score: "RW3-L4-S5" }, 
    { lastName: "Achury Romero", firstName: "Juan Antonio", exam: "YLE Movers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Hernández Bermúdez", firstName: "Luciana", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Rubio Pinto", firstName: "Ana María", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Abril Martínez", firstName: "Juan Andrés", exam: "YLE Movers", year: "2021", score: "Pending" }, 
    { lastName: "Achury Romero", firstName: "Daniel Eduardo", exam: "YLE Movers", year: "2021", score: "RW1-L2-S5" }, 
    { lastName: "Cárdenas Cáceres", firstName: "Catalina", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Castro Lombana", firstName: "Juan Pablo", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Coronado López", firstName: "Emilio", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Quintero Plazas", firstName: "Martín", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Rodríguez Caicedo", firstName: "Martin", exam: "YLE Movers", year: "2021", score: "RW1-L5-S5" }, 
    { lastName: "Ramírez Ruíz", firstName: "Juan David", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Acosta Gómez", firstName: "Jose Alejandro", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Garzón Navas", firstName: "Laura Zulay", exam: "YLE Movers", year: "2021", score: "RW1-L5-S5" }, 
    { lastName: "Buitrago Díaz", firstName: "Gabriel", exam: "YLE Movers", year: "2021", score: "Pending" }, 
    { lastName: "Guerra Peña", firstName: "Ana Isabel", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Uribe Patiño", firstName: "Luciana", exam: "YLE Movers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Bernal Bernal", firstName: "lan Marco", exam: "YLE Movers", year: "2021", score: "RW1-L5-S5" }, 
    { lastName: "Gutiérrez Beltrán", firstName: "Juan Pablo", exam: "YLE Movers", year: "2021", score: "Pending" }, 
    { lastName: "Huertas Agudelo", firstName: "Samuel Felipe", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Peña Ibañez", firstName: "Juliana Andrea", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Ardila Buitrago", firstName: "Sebastián", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Bermúdez Pineda", firstName: "Manuela", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Cely Pardo", firstName: "Samuel", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "Lobo Soto", firstName: "Sebastián", exam: "YLE Movers", year: "2021", score: "RW1-L5-S5" }, 
    { lastName: "Castro Delgado", firstName: "Miguel Dario", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Ramírez Velandia", firstName: "Isabella", exam: "YLE Movers", year: "2021", score: "RW2-L3-S5" }, 
    { lastName: "Rico Méndez", firstName: "Ana Isabella", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Stoyanovich Lozano", firstName: "Angelo", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Avendaño Moreno", firstName: "Julián Santiago", exam: "YLE Movers", year: "2021", score: "RW1-L4-S3" }, 
    { lastName: "Álvarez Gelvez", firstName: "Támara Andrea", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "González Fernández", firstName: "Shayra Vanessa", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "Velásquez Medina", firstName: "Juan Sebastián", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Aguilera Valencia", firstName: "Miranda", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Alarcón Pareja", firstName: "Simón", exam: "YLE Movers", year: "2021", score: "Pending" }, 
    { lastName: "Collazos Cortés", firstName: "Juan Manuel", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Cortés Porras", firstName: "Samuel Yecid", exam: "YLE Movers", year: "2021", score: "RW1-L3-S4" }, 
    { lastName: "Gómez Romero", firstName: "Juan José", exam: "YLE Movers", year: "2021", score: "RW1-L1-S4" }, 
    { lastName: "Másmela Hernández", firstName: "Silvana", exam: "YLE Movers", year: "2021", score: "RW1-L3-S5" }, 
    { lastName: "Cejas Cely", firstName: "Martin", exam: "YLE Movers", year: "2021", score: "RW1-L4-S5" }, 
    { lastName: "Garzón Baquero", firstName: "Josué", exam: "YLE Movers", year: "2021", score: "RW1-L1-S4" }, 
    { lastName: "López Cañón", firstName: "Juan Diego", exam: "YLE Movers", year: "2021", score: "RW1-L3-S4" }, 
    { lastName: "León Uribe", firstName: "Juan José", exam: "YLE Movers", year: "2021", score: "RW1-L1-S5" }, 
    { lastName: "Amortegui Ramírez", firstName: "Matías", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "Roa Sepulveda", firstName: "Lorenzo", exam: "YLE Movers", year: "2021", score: "RW3-L4-S5" }, 
    { lastName: "Bernal Rodríguez", firstName: "Luis Alejandro", exam: "YLE Movers", year: "2021", score: "RW1-L1-S5" }, 
    { lastName: "Vargas Pisciotti", firstName: "Luciana", exam: "YLE Movers", year: "2021", score: "RW1-L4-S5" }, 
    { lastName: "Medina Ardila", firstName: "Luciana", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "Durán Moreno", firstName: "Tomás", exam: "YLE Movers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Carreño Torres", firstName: "Diego Alejandro", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Cardona Villaruel", firstName: "Sebastián", exam: "YLE Movers", year: "2021", score: "RW3-L5-S4" }, 
    { lastName: "Garzón Díaz", firstName: "María Camila", exam: "YLE Movers", year: "2021", score: "RW1-L5-S5" }, 
    { lastName: "Vargas Aullón", firstName: "Sofía María", exam: "YLE Movers", year: "2021", score: "RW2-L5-S4" }, 
    { lastName: "Muñoz Cárdenas", firstName: "Gabriel Felipe", exam: "YLE Movers", year: "2021", score: "Pending" }, 
    { lastName: "Clavijo Giraldo", firstName: "Carlos Eduardo", exam: "YLE Movers", year: "2021", score: "RW2-L5-S5" }, 
    { lastName: "Rodríguez Díaz", firstName: "Samuel", exam: "YLE Movers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Murcia Barrera", firstName: "Juan Camilo", exam: "YLE Movers", year: "2021", score: "RW1-L1-S3" }, 
    { lastName: "Merchán Fontecha", firstName: "María Julieta", exam: "YLE Movers", year: "2021", score: "RW2-L4-S5" }, 
    { lastName: "Calderon Ferrer", firstName: "Isabella Maria", exam: "YLE Movers", year: "2021", score: "RW3-L4-S5" }, 
    { lastName: "Gallego Cespedes", firstName: "Sophia", exam: "YLE Movers", year: "2021", score: "RW2-L4-S4" },

    
// Data from ResultsSummary_YLE_Movers_30_AUGUST_2022.pdf

  { lastName: "ARAUJO CUADROS", firstName: "MARÍA CAMILA", exam: "YLE Movers", year: "2022", score: "RW3-L4-S5" },
  { lastName: "ARIAS AREVALO", firstName: "JUAN JOSÉ", exam: "YLE Movers", year: "2022", score: "RW1-L3-S5" },
  { lastName: "AVENDAÑO BARÓN", firstName: "JUAN PABLO", exam: "YLE Movers", year: "2022", score: "RW3-L5-S5" },
  { lastName: "BOTÓN PABÓN", firstName: "SIMON MAURICIO", exam: "YLE Movers", year: "2022", score: "RW4-L5-S5" },
  { lastName: "CAMACHO PINILLA", firstName: "MATHIAS", exam: "YLE Movers", year: "2022", score: "RW1-L4-S5" },
  { lastName: "CAMARGO ANDRADE", firstName: "PEDRO FELIPE", exam: "YLE Movers", year: "2022", score: "RW4-L5-S5" },
  { lastName: "CAMPO VERGARA", firstName: "SARA SOFIA", exam: "YLE Movers", year: "2022", score: "Pending" },
  { lastName: "CASTILLO BOTÓN", firstName: "JUAN MARTÍN", exam: "YLE Movers", year: "2022", score: "RW3-L4-S5" },
  { lastName: "CASTILLO RODRÍGUEZ", firstName: "SARA SOFÍA", exam: "YLE Movers", year: "2022", score: "RW5-L5-S5" },
  { lastName: "ECHEVERRÍA MEDRANO", firstName: "EMILIANO", exam: "YLE Movers", year: "2022", score: "RW3-L3-S5" },
  { lastName: "FORIGUA BARRERA", firstName: "MARÍA ALEJANDRA", exam: "YLE Movers", year: "2022", score: "RW2-L3-S5" },
  { lastName: "FRANCO MUÑOZ", firstName: "GEORGE DYLAN", exam: "YLE Movers", year: "2022", score: "RW2-L3-S3" },
  { lastName: "GALVIZ RUBIO", firstName: "ESTEBAN", exam: "YLE Movers", year: "2022", score: "RW2-L4-S4" },
  { lastName: "GARZÓN MEDINA", firstName: "GABRIELA", exam: "YLE Movers", year: "2022", score: "RW5-L4-S5" },
  { lastName: "GAVIRIA ORJUELA", firstName: "SANTIAGO", exam: "YLE Movers", year: "2022", score: "RW2-L4-S3" },
  { lastName: "GORUT NIETO", firstName: "MARIANGEL", exam: "YLE Movers", year: "2022", score: "RW3-L4-S4" },
  { lastName: "GUERRA CORTÉS", firstName: "ADRIÁN", exam: "YLE Movers", year: "2022", score: "RW4-L4-S5" },
  { lastName: "GUERRA URIBE", firstName: "LIAN MARTIN", exam: "YLE Movers", year: "2022", score: "RW4-L4-S5" },
  { lastName: "GUTIÉRREZ CHAMORRO", firstName: "VALENTINA", exam: "YLE Movers", year: "2022", score: "RW2-L4-S5" },
  { lastName: "HERREÑO RODRÍGUEZ", firstName: "SAMANTHA", exam: "YLE Movers", year: "2022", score: "RW1-L3-S5" },
  { lastName: "HIGUERA LÓPEZ", firstName: "SARA ISABELLA", exam: "YLE Movers", year: "2022", score: "RW1-L1-S2" },
  { lastName: "JARA LOZANO", firstName: "ANDERSÓN", exam: "YLE Movers", year: "2022", score: "RW1-L2-S3" },
  { lastName: "JIMENEZ ESPINOSA", firstName: "MARÍA ALEJANDRA", exam: "YLE Movers", year: "2022", score: "RW4-L4-S5" },
  { lastName: "LANCHEROS SILVA", firstName: "ANA MARÍA", exam: "YLE Movers", year: "2022", score: "RW1-L4-S5" },
  { lastName: "LEÓN GUTIERREZ", firstName: "MARIANA GABRIELA", exam: "YLE Movers", year: "2022", score: "RW1-L2-S3" },
  { lastName: "LOAIZA PINTO", firstName: "IVAN DAVID", exam: "YLE Movers", year: "2022", score: "RW2-L4-S5" },
  { lastName: "LÓPEZ VILLAMIL", firstName: "SAMUEL ALEJANDRO", exam: "YLE Movers", year: "2022", score: "RW3-L3-S5" },
  { lastName: "LOZANO BUITRAGO", firstName: "PAULINA", exam: "YLE Movers", year: "2022", score: "RW5-L5-S4" },
  { lastName: "LUENGAS MENDOZA", firstName: "ANTONIA", exam: "YLE Movers", year: "2022", score: "RW4-L4-S5" },
  { lastName: "MANOTAS TEJEDOR", firstName: "ENRIQUE", exam: "YLE Movers", year: "2022", score: "RW3-L3-S5" },
  { lastName: "MARÍN CABEZAS", firstName: "PAULO CESAR", exam: "YLE Movers", year: "2022", score: "RW1-L4-S3" },
  { lastName: "MORA BECERRA", firstName: "JUAN DIEGO", exam: "YLE Movers", year: "2022", score: "RW1-L4-S5" },
  { lastName: "MUÑOZ GUARNIZO", firstName: "GIBRAN ARLEY", exam: "YLE Movers", year: "2022", score: "RW1-L4-S4" },
  { lastName: "NIETO GUERRERO", firstName: "LUIS ANTONIO", exam: "YLE Movers", year: "2022", score: "RW5-L4-S5" },
  { lastName: "ORTIZ NAVARRO", firstName: "JOSHUA", exam: "YLE Movers", year: "2022", score: "RW3-L4-S5" },
  { lastName: "PARRA PULIDO", firstName: "GABRIEL", exam: "YLE Movers", year: "2022", score: "RW3-L3-S5" },
  { lastName: "RAMOS LÓPEZ", firstName: "JUAN MARTÍN", exam: "YLE Movers", year: "2022", score: "RW5-L5-S5" },
  { lastName: "RUEDA OSORIO", firstName: "JUAN MARTÍN", exam: "YLE Movers", year: "2022", score: "RW5-L5-S5" },
  { lastName: "SAAVEDRA GALLEGO", firstName: "TOMÁS", exam: "YLE Movers", year: "2022", score: "RW1-L2-S4" },
  { lastName: "SERRANO JAIME", firstName: "DANIEL FELIPE", exam: "YLE Movers", year: "2022", score: "RW2-L3-S5" },
  { lastName: "TAMAYO VILLAMIL", firstName: "JUAN CAMILO", exam: "YLE Movers", year: "2022", score: "RW2-L4-S5" },
  { lastName: "VARELA NIÑO", firstName: "JOAQUÍN ANDRÉS", exam: "YLE Movers", year: "2022", score: "RW2-L4-S5" },
  { lastName: "VARGAS BELTRÁN", firstName: "MARIA LUCIA", exam: "YLE Movers", year: "2022", score: "RW3-L4-S5" },
  { lastName: "GARCIA GUTIERREZ", firstName: "JUAN DAVID", exam: "YLE Movers", year: "2022", score: "RW1-L1-S4" },
  { lastName: "GALINDO PARDO", firstName: "SANTIAGO", exam: "YLE Movers", year: "2022", score: "RW1-L4-S5" },
  
    // Data from ResultsSummary_YLE_Movers_30_AUGUST_2023.pdf

  { lastName: "Pino Toloza", firstName: "Isabella", exam: "YLE Movers", year: "2023", score: "Pending" },
  { lastName: "Olarte Giraldo", firstName: "Andrés", exam: "YLE Movers", year: "2023", score: "RW2-L5-S5" },
  { lastName: "Ariza Corredor", firstName: "Danna Sofía", exam: "YLE Movers", year: "2023", score: "RW3-L5-S5" },
  { lastName: "Blanco Parra", firstName: "Juan Diego", exam: "YLE Movers", year: "2023", score: "RW4-L4-S5" },
  { lastName: "Baron Gutiérrez", firstName: "Juana Isabella", exam: "YLE Movers", year: "2023", score: "RW5-L5-S5" },
  { lastName: "Ramírez Jiménez", firstName: "Martín", exam: "YLE Movers", year: "2023", score: "RW2-L3-S5" },
  { lastName: "Gómez Gallego", firstName: "Johan Matias", exam: "YLE Movers", year: "2023", score: "RW1-L1-S4" },
  { lastName: "García Fresneda", firstName: "Santiago", exam: "YLE Movers", year: "2023", score: "RW1-L2-S3" },
  { lastName: "Pacheco Vega", firstName: "Valeria", exam: "YLE Movers", year: "2023", score: "RW2-L1-S4" },
  { lastName: "Bustamante Celis", firstName: "Verónica", exam: "YLE Movers", year: "2023", score: "RW3-L4-S5" },
  { lastName: "Mariño Fuentes", firstName: "Maria Alejandra", exam: "YLE Movers", year: "2023", score: "RW4-L4-S2" },
  { lastName: "Cardoso Niño", firstName: "Alvaro", exam: "YLE Movers", year: "2023", score: "RW1-L1-S4" },
  { lastName: "Blanco Parra", firstName: "Jose Alejandro", exam: "YLE Movers", year: "2023", score: "RW2-L3-S4" },
  { lastName: "Castro Delgado", firstName: "Juan Emilio", exam: "YLE Movers", year: "2023", score: "RW1-L1-S3" },
  { lastName: "Prieto Sánchez", firstName: "Emilio", exam: "YLE Movers", year: "2023", score: "RW4-L5-S5" },
  { lastName: "Gómez Carrascal", firstName: "Juan José", exam: "YLE Movers", year: "2023", score: "RW5-L4-S5" },
  { lastName: "Durán Gómez", firstName: "Ana Victoria", exam: "YLE Movers", year: "2023", score: "RW3-L4-S5" },
  { lastName: "Torres Devia", firstName: "Andrey Felipe", exam: "YLE Movers", year: "2023", score: "RW1-L1-S5" },
  { lastName: "Cuella Martínez", firstName: "Camila", exam: "YLE Movers", year: "2023", score: "RW5-L5-S5" },
  { lastName: "Ávila Martínez", firstName: "Isabel Gabriela", exam: "YLE Movers", year: "2023", score: "RW4-L3-S5" },
  { lastName: "Ramos Parra", firstName: "María Juliana", exam: "YLE Movers", year: "2023", score: "RW3-L3-S5" },
  { lastName: "Arocha Latorre", firstName: "Tomás", exam: "YLE Movers", year: "2023", score: "RW5-L5-S5" },
  { lastName: "Tello Ortiz", firstName: "Libia Sofía", exam: "YLE Movers", year: "2023", score: "RW5-L5-S5" },
  { lastName: "David Ferrucho", firstName: "Iván Santiago", exam: "YLE Movers", year: "2023", score: "RW2-L3-S5" },
  { lastName: "Castro Contreras", firstName: "Juan Diego", exam: "YLE Movers", year: "2023", score: "RW2-L4-S5" },
  { lastName: "Guamán Lancheros", firstName: "María Juliana", exam: "YLE Movers", year: "2023", score: "RW4-L4-S5" },
  { lastName: "Grosso Prieto", firstName: "Jacobo", exam: "YLE Movers", year: "2023", score: "RW4-L3-S5" },
  { lastName: "Méndez Bonilla", firstName: "Juan José", exam: "YLE Movers", year: "2023", score: "RW4-L4-S5" },
  { lastName: "Rincón Camacho", firstName: "Salomé", exam: "YLE Movers", year: "2023", score: "RW3-L4-S5" },
  { lastName: "Tamayo Chaparro", firstName: "Verónica", exam: "YLE Movers", year: "2023", score: "RW2-L4-S5" },
  { lastName: "Cardona Villarruel", firstName: "Santiago", exam: "YLE Movers", year: "2023", score: "RW3-L3-S4" },
  { lastName: "Niño Hernández", firstName: "Ashley Julieth", exam: "YLE Movers", year: "2023", score: "RW2-L5-S5" },
  { lastName: "Pinzón Ramirez", firstName: "Juan Esteban", exam: "YLE Movers", year: "2023", score: "RW5-L5-S5" },
  { lastName: "Cuadrado Samboni", firstName: "Salome", exam: "YLE Movers", year: "2023", score: "RW3-L4-S5" },
  { lastName: "Blanco López", firstName: "Miguel Ángel", exam: "YLE Movers", year: "2023", score: "RW1-L1-S5" },

    // Data from ResultsSummary_YLE_Movers_15_AUGUST_2024.pdf
    { lastName: "ABOUZELOF FORERO", firstName: "SAID", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "ECHEVERRIA MEDRANO", firstName: "ELIANA", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "FAJARDO PINZÓN", firstName: "MARIA PAULA", exam: "YLE Movers", year: "2024", score: "RW2-L4-S4" },
    { lastName: "GARZON ZAMORA", firstName: "MATIAS JESE", exam: "YLE Movers", year: "2024", score: "RW2-L3-S5" },
    { lastName: "LOBOGUERRERO ULLOA", firstName: "JUAN DIEGO", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "NOGUEIRA CONSIDERA", firstName: "MILENA", exam: "YLE Movers", year: "2024", score: "RW2-L5-S5" },
    { lastName: "PERALTA FRANCO", firstName: "SEBASTIÁN", exam: "YLE Movers", year: "2024", score: "RW4-L4-S5" },
    { lastName: "QUINTANA CAMACHO", firstName: "MARÍA JULIANA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "SALAMANCA CHAPARRO", firstName: "SANTIAGO", exam: "YLE Movers", year: "2024", score: "RW2-L3-S5" },
    { lastName: "USECHE REYES", firstName: "ANA MARÍA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S4" },
    { lastName: "VANEGAS GONZALEZ", firstName: "ESTEBAN", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "VARELA NIÑO", firstName: "JULIETA MARÍA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "CASTRO VARGAS", firstName: "LUZ GABRIELA", exam: "YLE Movers", year: "2024", score: "RW2-L5-S5" },
    { lastName: "PEREZ ARIAS", firstName: "SEBASTIÁN", exam: "YLE Movers", year: "2024", score: "RW1-L4-S5" },
    { lastName: "PAIPA PEÑA", firstName: "ALEJANDRO", exam: "YLE Movers", year: "2024", score: "RW1-L4-S5" },
    { lastName: "MACHUCA APONTE", firstName: "JERONIMO", exam: "YLE Movers", year: "2024", score: "RW1-L4-S5" },
    { lastName: "LÓPEZ MARTÍNEZ", firstName: "SARA LUCIANA", exam: "YLE Movers", year: "2024", score: "RW4-L4-S5" },
    { lastName: "MARÍN PATIÑO", firstName: "GABRIEL HUMBERTO", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "GUDIÑO ALVAREZ", firstName: "ALVARO ALEJANDRO", exam: "YLE Movers", year: "2024", score: "RW2-L4-S5" },
    { lastName: "FLOREZ MEDINA", firstName: "SALOMÉ", exam: "YLE Movers", year: "2024", score: "RW1-L3-S4" },
    { lastName: "VARGAS PULIDO", firstName: "MARÍA PAULA", exam: "YLE Movers", year: "2024", score: "RW2-L4-S5" },
    { lastName: "MAYA BASTIDAS", firstName: "JERÓNIMO", exam: "YLE Movers", year: "2024", score: "RW3-L4-S5" },
    { lastName: "ALFONSO ARISTIZABAL", firstName: "CRISTOBAL", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "CAÑÓN BAYONA", firstName: "GABRIELA", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "CHAYA VERJEL", firstName: "MATEO ALBERTO", exam: "YLE Movers", year: "2024", score: "RW2-L4-S5" },
    { lastName: "CRISTANCHO TELLO", firstName: "SAMUEL", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "DURÁN GÓMEZ", firstName: "JUAN DAVID", exam: "YLE Movers", year: "2024", score: "RW1-L5-S5" },
    { lastName: "DURÁN MORENO", firstName: "MARÍA EMILIA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "FORERO ROMERO", firstName: "JOSE GUILLERMO", exam: "YLE Movers", year: "2024", score: "RW2-L5-S5" },
    { lastName: "GARCÍA MONTOYA", firstName: "VALENTINA", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "GÓMEZ SÁNCHEZ", firstName: "MARTÍN FRANCISCO", exam: "YLE Movers", year: "2024", score: "RW1-L4-S5" },
    { lastName: "GONZALEZ MONTES", firstName: "MARTÍN", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "GUEVARA ESCOVAR", firstName: "LUCAS", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "MACIAS PERICO", firstName: "DAVID SANTIAGO", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "MARTÍN DÍAZ", firstName: "VALENTINA", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "MÉNDEZ SARMIENTO", firstName: "JUANA LUCIA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "NOVOA MARÍN", firstName: "JERÓNIMO", exam: "YLE Movers", year: "2024", score: "RW1-L3-S4" },
    { lastName: "OSPINO AYA", firstName: "JUAN DIEGO", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "PRIETO RODRÍGUEZ", firstName: "JOAQUÍN", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "RODRÍGUEZ TOCA", firstName: "ESTEBAN", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "SAAVEDRA GONZÁLEZ", firstName: "DIANA ALEJANDRA", exam: "YLE Movers", year: "2024", score: "RW2-L4-S5" },
    { lastName: "SALINAS GUIO", firstName: "DANTE", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "TRUJILLO ESPITALETA", firstName: "JUAN JACOBO", exam: "YLE Movers", year: "2024", score: "RW1-L5-S5" },
    { lastName: "YATE REYES", firstName: "JUAN PABLO", exam: "YLE Movers", year: "2024", score: "RW3-L4-S5" },
    { lastName: "ARRIETA LORDUY", firstName: "SALOMÓN", exam: "YLE Movers", year: "2024", score: "RW1-L2-S3" },
    { lastName: "AZA ESPINOSA", firstName: "JUANITA", exam: "YLE Movers", year: "2024", score: "RW2-L5-S4" },
    { lastName: "CÁRDENAS MORENO", firstName: "OMAR SANTIAGO", exam: "YLE Movers", year: "2024", score: "RW4-L4-S4" },
    { lastName: "CARVAJAL CUERVO", firstName: "VALERIA", exam: "YLE Movers", year: "2024", score: "RW1-L4-S4" },
    { lastName: "CASTRO RODRÍGUEZ", firstName: "PABLO", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "DÍAZ MALDONADO", firstName: "VICTORIA", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "GALINDO TARAZONA", firstName: "JOEL JERÓNIΜΟ", exam: "YLE Movers", year: "2024", score: "RW1-L2-S3" },
    { lastName: "MARTÍNEZ OVALLE", firstName: "JUANITA", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "MARTÍNEZ RODRÍGUEZ", firstName: "TOMÁS", exam: "YLE Movers", year: "2024", score: "RW1-L5-S5" },
    { lastName: "MIRANDA RAMÍREZ", firstName: "ANTONELLA", exam: "YLE Movers", year: "2024", score: "RW1-L4-S4" },
    { lastName: "MUÑOZ FRANCO", firstName: "NATALIA", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "NIETO GUERRERO", firstName: "VICTORIA ELENA", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "NIÑO RODRÍGUEZ", firstName: "JUAN JOSÉ", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "PARDO OROZCO", firstName: "ESTEBAN ANDRES", exam: "YLE Movers", year: "2024", score: "RW2-L4-S5" },
    { lastName: "PARRA PULIDO", firstName: "MARIA PAULA", exam: "YLE Movers", year: "2024", score: "RW2-L5-S5" },
    { lastName: "ROA BENITO", firstName: "JUAN JOSÉ", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "RODRÍGUEZ DÍAZ", firstName: "ISAAC", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },
    { lastName: "RUÍZ MANRIQUE", firstName: "CRISTIAN JULIÁN", exam: "YLE Movers", year: "2024", score: "RW2-L5-S5" },
    { lastName: "SOLARTE GUERRERO", firstName: "EMILIANO", exam: "YLE Movers", year: "2024", score: "RW3-L5-S5" },
    { lastName: "TANGARIFE GARZÓN", firstName: "EAN JOEL", exam: "YLE Movers", year: "2024", score: "RW4-L5-S5" },
    { lastName: "TRUJILLO TOVAR", firstName: "ALEJANDRO", exam: "YLE Movers", year: "2024", score: "RW1-L4-S5" },
    { lastName: "LEGUIZAMON ROMERO", firstName: "EMILIANO", exam: "YLE Movers", year: "2024", score: "RW5-L5-S5" },

    // Data from ResultsSummary_YLE_Movers_03_SEPTEMBER_2025.pdf
    { lastName: "ACOSTA VASQUEZ", firstName: "ISABELLA", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "BUENO MORENO", firstName: "MATIAS", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "CAICEDO NÁRVAEZ", firstName: "JUAN MARTÍN", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "CÁRDENAS ROMERO", firstName: "SANTIAGO ENRIQUE", exam: "YLE Movers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "CASADIEGOS LONDOÑO", firstName: "GABRIELA", exam: "YLE Movers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "CASTELBLANCO ROMERO", firstName: "EVELYN", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "DUQUE RODRIGUEZ", firstName: "MARTIN EMILIO", exam: "YLE Movers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "ESCOBAR GOYES", firstName: "VALENTINA", exam: "YLE Movers", year: "2025", score: "Pending" }, 
    { lastName: "GARCÍA GONZÁLEZ", firstName: "GABRIEL", exam: "YLE Movers", year: "2025", score: "RW1-L5-S5" }, 
    { lastName: "GARCÍA GUTIÉRREZ", firstName: "FELIPE", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "GARZÓN BOTERO", firstName: "SAMUEL", exam: "YLE Movers", year: "2025", score: "RW3-L3-S4" }, 
    { lastName: "GONZÁLEZ CANTOR", firstName: "SAMUEL", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "GUTIERREZ CASTRO", firstName: "ANDRÉS DAVID", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "LOAIZA PIΝΤΟ", firstName: "IAN SANTIAGO", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "MONDRAGÓN TORRES", firstName: "JUAN JOSÉ", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "MONTAÑO GARCÍA", firstName: "ΑΝΤΟΝΙΑ", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "MUNEVAR DUITAMA", firstName: "JULIETA", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "PASTRANA CALDERON", firstName: "GABRIEL", exam: "YLE Movers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "RINCON MARIÑO", firstName: "RAFAELLA", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "SAAVEDRA GALLEGO", firstName: "MARIANA", exam: "YLE Movers", year: "2025", score: "RW1-L3-S5" }, 
    { lastName: "SERRANO PULIDO", firstName: "TOMÁS", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "SILVA GARCÍA", firstName: "GABRIELA VALENTINA", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "TORRALBA ROJAS", firstName: "AURA LUCIA", exam: "YLE Movers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "FONTALVO SALAS", firstName: "JUAN FELIPE", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "AGUILERA MORENO", firstName: "GABRIELA", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "ALTAHONA BUITRAGO", firstName: "JUAN JOSÉ", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "ARIAS CRUZ", firstName: "ALEJANDRA", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "AYALA ECHEVERRY", firstName: "DANIEL FELIPE", exam: "YLE Movers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "BLANCO LÓPEZ", firstName: "KATIA MARCELA", exam: "YLE Movers", year: "2025", score: "RW1-L3-S4" }, 
    { lastName: "CAICEDO BENAVIDES", firstName: "JOAQUIN", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "CORONADO", firstName: "JACOBO", exam: "YLE Movers", year: "2025", score: "RW1-L3-S4" }, 
    { lastName: "DÍAZ ORTEGÓN", firstName: "JUAN JOSÉ NICACIO", exam: "YLE Movers", year: "2025", score: "RW1-L3-S5" }, 
    { lastName: "FONTALVO SALAS", firstName: "DANIELA", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "FORIGUA BARRERA", firstName: "SANTIAGO EDUARDO", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "GARCÍA CASAS", firstName: "LUCIANA", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "JARA LOZANO", firstName: "VALERIE", exam: "YLE Movers", year: "2025", score: "RW1-L3-S5" }, 
    { lastName: "LOZANO BUITRAGO", firstName: "LORENZO", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "MALDONADO BEDOYA", firstName: "MARIANA", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "MORA CALDERÓN", firstName: "ETHAN", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "MUÑOZ GÓMEZ", firstName: "THOMÁS", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "ORTIZ NIÑO", firstName: "HANNA", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "PEREIRA ARIZA", firstName: "JOEL SANTIAGO", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "PINZÓN GONZÁLEZ", firstName: "DANNA", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "RICO MOLINA", firstName: "LUIS IGNACIO", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "ROJAS FLÓREZ", firstName: "ISABELLA", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "SIERRA ALZATE", firstName: "GABRIEL", exam: "YLE Movers", year: "2025", score: "RW3-L4-S4" }, 
    { lastName: "SORDELLA JAIME", firstName: "MATEO", exam: "YLE Movers", year: "2025", score: "RW5-L5-S4" }, 
    { lastName: "TRIANA REYES", firstName: "MARÍA VICTORIA", exam: "YLE Movers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "ALMANZA MURCIA", firstName: "GABRIELA", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "AZAR DAZA", firstName: "JAEL", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "BONILLA URUEÑA", firstName: "DAVID ANDRÉS", exam: "YLE Movers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "CASTILLO MONROY", firstName: "JUAN ANDRÉS", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "CORONADO JIMÉNEZ", firstName: "ANDRÉS FELIPE", exam: "YLE Movers", year: "2025", score: "RW1-L3-S4" }, 
    { lastName: "DÍAZ GOMEZ", firstName: "SAMUEL", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "GÓMEZ CHIQUILLO", firstName: "BENJAMÍN TOMÁS", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "GONZÁLEZ HOYOS", firstName: "MARTÍN", exam: "YLE Movers", year: "2025", score: "RW2-L5-S5" }, 
    { lastName: "GORDILLO MIRANDA", firstName: "JOAQUÍN", exam: "YLE Movers", year: "2025", score: "RW2-L2-S4" }, 
    { lastName: "GUERRERO FLECHAS", firstName: "FLORENCIA", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "GUTIÉRREZ LUIS", firstName: "ANDRÉS CAMILO", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "LÓPEZ LÓPEZ", firstName: "LUIS SANTIAGO", exam: "YLE Movers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "MACIAS PERICO", firstName: "LUCIANA", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "MONTILLA SIERRA", firstName: "SEBASTIÁN MAURICIO", exam: "YLE Movers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "MORALES FERIA", firstName: "MARTINA", exam: "YLE Movers", year: "2025", score: "RW2-L5-S5" }, 
    { lastName: "MUÑOZ CORREA", firstName: "VIOLETTA", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "NÁRVAEZ ZAMBRANO", firstName: "MARÍA PAZ", exam: "YLE Movers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "PALACIOS HERNÁNDEZ", firstName: "MARÍA JOSÉ", exam: "YLE Movers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "PINZÓN FONSECA", firstName: "VALENTINA", exam: "YLE Movers", year: "2025", score: "Pending" }, 
    { lastName: "RODRÍGUEZ MUÑOZ", firstName: "ΑΝΤΟΝΙΑ", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "SIERRA ALZATE", firstName: "SANTIAGO", exam: "YLE Movers", year: "2025", score: "RW2-L5-S5" }, 
    { lastName: "VALENCIA LOZANO", firstName: "SOFÍA", exam: "YLE Movers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "ÁRDILA CASAS", firstName: "SARA", exam: "YLE Movers", year: "2025", score: "RW2-L5-S5" },

    
   
    // Data from ResultsSummary_YLE_Flyers_07_OCTOBER_2021.pdf
    { lastName: "Abdul Latif", firstName: "Sami Fadi", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Calderon Martinez", firstName: "Samuel", exam: "YLE Flyers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Forero Herrera", firstName: "Zarah Daniela", exam: "YLE Flyers", year: "2021", score: "RW1-L2-S5" }, 
    { lastName: "Ojeda Ayala", firstName: "Carlos David", exam: "YLE Flyers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Pino Manzano", firstName: "Mariana Alejandra", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Ramirez Quiroz", firstName: "Samuel Esteban", exam: "YLE Flyers", year: "2021", score: "RW3-L4-S5" }, 
    { lastName: "Vanegas Lopez", firstName: "Jose Manuel", exam: "YLE Flyers", year: "2021", score: "RW1-L1-S5" }, 
    { lastName: "Alvarez Gelvez", firstName: "Naia Alejandra", exam: "YLE Flyers", year: "2021", score: "RW5-L4-S5" }, 
    { lastName: "Enciso Monroy", firstName: "Manuela", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Marin Padilla", firstName: "Manuel Andres", exam: "YLE Flyers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Pardo Correa", firstName: "Mariana", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Velásquez Medina", firstName: "Mariana", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Sandoval Serna", firstName: "Duvan Alejandro", exam: "YLE Flyers", year: "2021", score: "RW1-L1-S4" }, 
    { lastName: "Carreño Castelblanco", firstName: "Sebastian", exam: "YLE Flyers", year: "2021", score: "RW5-L4-S5" }, 
    { lastName: "Salazar Nieto", firstName: "Maria Alejandra", exam: "YLE Flyers", year: "2021", score: "RW4-L3-S5" }, 
    { lastName: "Maldonado Correa", firstName: "Santiago", exam: "YLE Flyers", year: "2021", score: "RW2-L1-S5" }, 
    { lastName: "Alzate Lovera", firstName: "Samuel", exam: "YLE Flyers", year: "2021", score: "RW3-L3-S5" }, 
    { lastName: "Bernal Delgado", firstName: "Rosario", exam: "YLE Flyers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Caina Gallego", firstName: "Juán Camilo", exam: "YLE Flyers", year: "2021", score: "Pending" }, 
    { lastName: "Franco Marín", firstName: "Juán Camilo", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Galindo Navarro", firstName: "Matias", exam: "YLE Flyers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Mahecha Torres", firstName: "Gabriella", exam: "YLE Flyers", year: "2021", score: "RW3-L5-S5" }, 
    { lastName: "Moreno Novoa", firstName: "Emilia", exam: "YLE Flyers", year: "2021", score: "RW5-L4-S5" }, 
    { lastName: "Pacheco Cañas", firstName: "Santiago", exam: "YLE Flyers", year: "2021", score: "Pending" }, 
    { lastName: "Restrepo Centeno", firstName: "Sofía", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Vesga Moreno", firstName: "Santiago", exam: "YLE Flyers", year: "2021", score: "RW4-L5-S5" }, 
    { lastName: "Betancourt Diaz", firstName: "Federico", exam: "YLE Flyers", year: "2021", score: "RW1-L1-S4" }, 
    { lastName: "Tobon", firstName: "Juan Sebastian", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Uribe Zuñiga", firstName: "Juan Jose", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Cuervo Lozada", firstName: "Jose Miguel", exam: "YLE Flyers", year: "2021", score: "RW1-L2-S5" }, 
    { lastName: "Delgado Tello", firstName: "Nicolas", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Rivera Muñoz", firstName: "Juan Diego", exam: "YLE Flyers", year: "2021", score: "RW1-L1-S4" }, 
    { lastName: "Orjuela Garcia", firstName: "Juan David", exam: "YLE Flyers", year: "2021", score: "RW3-L3-S4" }, 
    { lastName: "Suarez Hurtado", firstName: "Amelie", exam: "YLE Flyers", year: "2021", score: "RW4-L4-S5" }, 
    { lastName: "Castillo Rodriguez", firstName: "Daniel Alberto", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Zapata", firstName: "Mariana", exam: "YLE Flyers", year: "2021", score: "RW2-L3-S5" }, 
    { lastName: "Roldán", firstName: "Juan Sebastian", exam: "YLE Flyers", year: "2021", score: "Pending" }, 
    { lastName: "Arias Cruz", firstName: "Catalina", exam: "YLE Flyers", year: "2021", score: "RW5-L5-S5" }, 
    { lastName: "Cely", firstName: "Isabella", exam: "YLE Flyers", year: "2021", score: "RW1-L1-S5" }, 
    { lastName: "Rojas Ramirez", firstName: "Samuel Andres", exam: "YLE Flyers", year: "2021", score: "RW2-L2-S5" }, 

    // Data from ResultsSummary_YLE_Flyers_31_AUGUST_2022.pdf
    { lastName: "ARDILA", firstName: "DANNA", exam: "YLE Flyers", year: "2022", score: "RW4-L4-S5" }, 
    { lastName: "BELTRAN GARAVITO", firstName: "SAMUEL JOSÉ", exam: "YLE Flyers", year: "2022", score: "RW2-L3-S4" }, 
    { lastName: "BERNÁL", firstName: "ESTEBAN", exam: "YLE Flyers", year: "2022", score: "RW2-L2-S5" }, 
    { lastName: "CAMARGO", firstName: "MARIA ALEJANDRA", exam: "YLE Flyers", year: "2022", score: "RW4-L4-S5" }, 
    { lastName: "CASAS DIAZ", firstName: "JAIRO SANTIAGO", exam: "YLE Flyers", year: "2022", score: "RW2-L4-S5" }, 
    { lastName: "CASTIBLANCO", firstName: "MARTIN", exam: "YLE Flyers", year: "2022", score: "RW2-L2-S5" }, 
    { lastName: "CELEITA", firstName: "ANA MARIA", exam: "YLE Flyers", year: "2022", score: "RW5-L5-S5" }, 
    { lastName: "CERVERA GALINDO", firstName: "MIGUEL ANGEL", exam: "YLE Flyers", year: "2022", score: "RW1-L1-S1" }, 
    { lastName: "DAVID FERRUCHO", firstName: "SARA VALENTINA", exam: "YLE Flyers", year: "2022", score: "RW3-L2-S5" }, 
    { lastName: "EHRHARDT", firstName: "ALEJANDRO", exam: "YLE Flyers", year: "2022", score: "RW2-L3-S4" }, 
    { lastName: "Gonzalez Posada", firstName: "Sophioa", exam: "YLE Flyers", year: "2022", score: "RW5-L5-S5" }, 
    { lastName: "GUTIÉRREZ MUNÉVAR", firstName: "JOSÉ IGNACIO", exam: "YLE Flyers", year: "2022", score: "RW4-L4-S5" }, 
    { lastName: "Henao Morа", firstName: "Juan Camilo", exam: "YLE Flyers", year: "2022", score: "RW5-L5-S5" }, 
    { lastName: "HERNÁNDEZ HERMOSA", firstName: "JUAN JERÓNIMO", exam: "YLE Flyers", year: "2022", score: "RW4-L3-S5" }, 
    { lastName: "Herrera Quenquan", firstName: "Miguel Angel", exam: "YLE Flyers", year: "2022", score: "RW2-L2-S5" }, 
    { lastName: "López Sandoval", firstName: "Gabriel", exam: "YLE Flyers", year: "2022", score: "RW1-L2-S5" }, 
    { lastName: "LOSADA ALVAREZ", firstName: "ANGEL EMMANUEL", exam: "YLE Flyers", year: "2022", score: "RW2-L3-S4" }, 
    { lastName: "Mila Cuadros", firstName: "Andrés Felipe", exam: "YLE Flyers", year: "2022", score: "RW4-L4-S5" }, 
    { lastName: "Munevar Montañez", firstName: "Juan Camilo", exam: "YLE Flyers", year: "2022", score: "RW5-L5-S5" }, 
    { lastName: "Ramirez Quiroz", firstName: "Juan Diego", exam: "YLE Flyers", year: "2022", score: "RW3-L3-S5" }, 
    { lastName: "ROJAS VILLAMIZAR", firstName: "TOMAS", exam: "YLE Flyers", year: "2022", score: "RW5-L5-S5" }, 
    { lastName: "SALINAS", firstName: "IRENE", exam: "YLE Flyers", year: "2022", score: "RW3-L2-S5" }, 
    { lastName: "SANCHEZ CASTRO", firstName: "SALOME", exam: "YLE Flyers", year: "2022", score: "RW4-L2-S5" }, 
    { lastName: "Sanchez Roncancio", firstName: "Mariana", exam: "YLE Flyers", year: "2022", score: "RW2-L1-S5" }, 
    { lastName: "SEQUERA", firstName: "JUAN SEBASTIAN", exam: "YLE Flyers", year: "2022", score: "RW3-L3-S5" }, 
    { lastName: "Sierra Moya", firstName: "Daniel", exam: "YLE Flyers", year: "2022", score: "RW3-L2-S4" }, 
    { lastName: "SARMIENTO MONTES", firstName: "JUAN DAVID", exam: "YLE Flyers", year: "2022", score: "RW2-L2-S5" }, 
    { lastName: "SAAVEDRA VELASQUEZ", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2022", score: "RW5-L4-S5" }, 
    { lastName: "GUÍO RAMIREZ", firstName: "LUCIANA", exam: "YLE Flyers", year: "2022", score: "RW2-L3-S5" }, 
    { lastName: "VILLABONA RINCÓN", firstName: "ALEJANDRO", exam: "YLE Flyers", year: "2022", score: "RW5-L3-S5" }, 
    { lastName: "CÉSPEDES", firstName: "ALEJANDRO", exam: "YLE Flyers", year: "2022", score: "RW3-L1-S4" }, 
    { lastName: "Villamil Giraldo", firstName: "Luis Alejandro", exam: "YLE Flyers", year: "2022", score: "RW1-L1-S5" }, 
    { lastName: "Chaux Escobar", firstName: "Sarah", exam: "YLE Flyers", year: "2022", score: "RW1-L1-S5" }, 

    // Data from ResultsSummary_YLE_Flyers_31_AUGUST_2023.pd
    { lastName: "ACHURY", firstName: "DANIEL EDUARDO", exam: "YLE Flyers", year: "2023", score: "RW3-L4-S4" }, 
    { lastName: "BERNAL PATΤΙΝΟ", firstName: "JUAN PAULO", exam: "YLE Flyers", year: "2023", score: "RW2-L4-S5" }, 
    { lastName: "CÁRDENAS CÁCERES", firstName: "CATALINA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "CASTRO LOMBANA", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "CEJAS CELY", firstName: "MARTIN", exam: "YLE Flyers", year: "2023", score: "RW3-L4-S5" }, 
    { lastName: "GÓMEZ CHIQUILLO", firstName: "SANTIAGO NICOLÁS", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "MEDINA ARDILA", firstName: "LUCIANA", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "PINILLA BLANDÓN", firstName: "MARIANNA", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "PISCAL TERÁN", firstName: "ISABELLA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "PARRA GALEANO", firstName: "SARA LUCÍA", exam: "YLE Flyers", year: "2023", score: "RW1-L3-S5" }, 
    { lastName: "DURÁN MORENO", firstName: "TOMÁS", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "ABRIL MARTÍNEZ", firstName: "ANDRÉS", exam: "YLE Flyers", year: "2023", score: "RW3-L4-S5" }, 
    { lastName: "ABELLO QUINTERO", firstName: "DAVID ALEJANDRO", exam: "YLE Flyers", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "ACOSTA GÓMEZ", firstName: "JOSÉ ALEJANDRO", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "ÁVILA MARTÍNEZ", firstName: "MARÍA ALEJANDRA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "HERNÁNDEZ BERMÚDEZ", firstName: "LUCIANA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "PEÑA IBAÑEZ", firstName: "JULIANA ANDREA", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "QUINTERO PLAZAS", firstName: "MARTİN", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "ROA SEPÚLVEDA", firstName: "LORENZO", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "RODRÍGUEZ DÍAZ", firstName: "SAMUEL", exam: "YLE Flyers", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "AMORTEGUI RAMÍREZ", firstName: "MATIAS", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "BERMUDEZ PINEDA", firstName: "MANUELA", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "GUERRA", firstName: "ANA ISABEL", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "GONZALEZ FERNÁNDEZ", firstName: "SHAYRA VANESSA", exam: "YLE Flyers", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "CLAVIJO GIRALDO", firstName: "CARLOS EDUARDO", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "FORERO AGUIRRE", firstName: "MARÁI ALEJANDRA", exam: "YLE Flyers", year: "2023", score: "RW2-L2-S5" }, 
    { lastName: "HERNANDEZ RIOS", firstName: "JUAN SEBASTIAN", exam: "YLE Flyers", year: "2023", score: "RW4-L3-S5" }, 
    { lastName: "CORTÉS PORRAS", firstName: "SAMUEL YESID", exam: "YLE Flyers", year: "2023", score: "RW2-L4-S5" }, 
    { lastName: "CÁRDENAS SERRANO", firstName: "JUAN JOSÉ", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "RODRIGUEZ CAICEDO", firstName: "MARTIN", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "TABARES MARIÑO", firstName: "MARIA CAMILA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "CORONADO LÓPEZ", firstName: "EMILIO", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "RAMIREZ RUÍZ", firstName: "JUAN DAVID", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "CELY PARDO", firstName: "SAMUEL", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "GARZÓN BAQUERO", firstName: "JOSUE", exam: "YLE Flyers", year: "2023", score: "RW1-L3-S5" }, 
    { lastName: "CASTRO DELGADO", firstName: "MIGUEL DARIO", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "RAMIREZ VELANDIA", firstName: "ISABELLA", exam: "YLE Flyers", year: "2023", score: "RW2-L2-S5" }, 
    { lastName: "AVENDAÑO MORENO", firstName: "JULIÁN SANTIAGO", exam: "YLE Flyers", year: "2023", score: "RW1-L4-S5" }, 
    { lastName: "DAVID ROSAS", firstName: "JORGE", exam: "YLE Flyers", year: "2023", score: "RW2-L3-S5" }, 
    { lastName: "HUERTAS AGUDELO", firstName: "SAMUEL FELIPE", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "STOYANOVICH LOZANO", firstName: "ANGELO", exam: "YLE Flyers", year: "2023", score: "RW5-L4-S5" }, 
    { lastName: "CARDONA VILLARUEL", firstName: "SEBASTIAN", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "CARREÑO TORRES", firstName: "DIEGO ALEJANDRO", exam: "YLE Flyers", year: "2023", score: "RW3-L4-S5" }, 
    { lastName: "LOBO SOTO", firstName: "SEBASTIAN", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 
    { lastName: "JIMENEZ RAMIREZ", firstName: "MARÍA JOSÉ", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "GARZÓN NAVAS", firstName: "LAURA ZULAY", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "CALDERÓN FERRER", firstName: "ISABELLA MARÍA", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "MÁSMELA HERNÁNDEZ", firstName: "SILVANA", exam: "YLE Flyers", year: "2023", score: "RW1-L1-S5" }, 
    { lastName: "GALLEGO CESPEDES", firstName: "SOPHIA", exam: "YLE Flyers", year: "2023", score: "RW2-L4-S5" }, 
    { lastName: "RIVERO ROMERO", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2023", score: "RW3-L3-S5" }, 
    { lastName: "ALARCÓN PAREJA", firstName: "SIMÓN", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "PINILLA PORRAS", firstName: "PABLO", exam: "YLE Flyers", year: "2023", score: "RW3-L3-S5" }, 
    { lastName: "ACHURY ROMERO", firstName: "JUAN ANTΟΝΙΟ", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "RUBIO PINTO", firstName: "ANA MARÍA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "BUITRAGO DÍAZ", firstName: "GABRIEL", exam: "YLE Flyers", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "TAMAYO CHAPARRO", firstName: "GABRIEL", exam: "YLE Flyers", year: "2023", score: "RW3-L5-S5" }, 
    { lastName: "COLLAZOS CORTÉS", firstName: "JUAN MANUEL", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "ALVAREZ PEÑA", firstName: "VIOLETA", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "SÁNCHEZ SALAS", firstName: "JUAN ANDRÉS", exam: "YLE Flyers", year: "2023", score: "RW5-L5-S5" }, 
    { lastName: "GUTIERREZ BELTRÁN", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2023", score: "RW4-L4-S5" }, 
    { lastName: "ROA CÁCERES", firstName: "JOSÉ DARIO", exam: "YLE Flyers", year: "2023", score: "RW2-L2-S5" }, 
    { lastName: "VELASQUEZ CAMACHO", firstName: "MARTIN", exam: "YLE Flyers", year: "2023", score: "RW2-L3-S5" }, 
    { lastName: "PORRAS MEDINA", firstName: "GABRIEL JAIME", exam: "YLE Flyers", year: "2023", score: "RW1-L1-S4" }, 
    { lastName: "CORSO BONILLA", firstName: "JUAN ESTEBAN", exam: "YLE Flyers", year: "2023", score: "RW2-L3-S5" }, 
    { lastName: "AGUILERA", firstName: "MIRANDA", exam: "YLE Flyers", year: "2023", score: "RW4-L5-S5" }, 


    // Data from ResultsSummary_YLE_Flyers_16_AUGUST_2024.pdf
    { lastName: "CALDERÓN CARVAJAL", firstName: "THOMÁS", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S4" }, 
    { lastName: "CARREÑO CASTELBLANCO", firstName: "LUCIANA", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CASTILLO RODRÍGUEZ", firstName: "SARA SOFÍA", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "DURAN MANOSALVA", firstName: "SIMÓN PABLO", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "GARCÍA GUTIÉRREZ", firstName: "JUAN DAVID", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "GARZÓN MEDINA", firstName: "GABRIELA", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "LEÓN GUTIÉRREZ", firstName: "MARIANA GABRIELA", exam: "YLE Flyers", year: "2024", score: "RW2-L5-S4" }, 
    { lastName: "MANOTAS TEJEDOR", firstName: "ENRIQUE", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "MANTILLA RIAÑO", firstName: "MARTÍN", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "MORA BECERRA", firstName: "JUAN DIEGO", exam: "YLE Flyers", year: "2024", score: "RW1-L5-S5" }, 
    { lastName: "ORTÍZ NAVARRO", firstName: "JOSHUA", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "OSPINA ARANGUREN", firstName: "MATEO", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "OSSES MATSUMI", firstName: "RYUKI", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "RAMOS LÓPEZ", firstName: "JUAN MARTÍN", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "SAAVEDRA GALLEGO", firstName: "TOMÁS", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "TAMAYO VILLAMIL", firstName: "JUAN CAMILO", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "TICONA ASTETE", firstName: "ARIADNA VALENTINA", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "VARELA NIÑO", firstName: "JOAQUÍN ANDRÉS", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "GARDIOL LEGRO", firstName: "JULIANA", exam: "YLE Flyers", year: "2024", score: "RW1-L2-S3" }, 
    { lastName: "PARRA PULIDO", firstName: "GABRIEL", exam: "YLE Flyers", year: "2024", score: "RW3-L3-S5" }, 
    { lastName: "ARAUJO CUADROS", firstName: "MARÍA CAMILA", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "ARDILA CASAS", firstName: "DANIEL", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "BONILLA ORTEGA", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CÁCERES GÓMEZ", firstName: "JAVIER MATIAS", exam: "YLE Flyers", year: "2024", score: "RW2-L2-S5" }, 
    { lastName: "CAICEDO MARTÍNEZ", firstName: "SOFÍA ISABELLA", exam: "YLE Flyers", year: "2024", score: "RW2-L2-S5" }, 
    { lastName: "CAMARGO ANDRADE", firstName: "PEDRO FELIPE", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "CUCAITA MEDINA", firstName: "JUAN IGNACIO", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "GALINDO PARDO", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "GUERRA CORTÉS", firstName: "ADRIÁN", exam: "YLE Flyers", year: "2024", score: "RW5-L3-S5" }, 
    { lastName: "JARA LOZANO", firstName: "ANDERSON", exam: "YLE Flyers", year: "2024", score: "RW2-L2-S4" }, 
    { lastName: "LUENGAS MENDOZA", firstName: "ΑΝΤΟΝΙΑ", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "MANTILLA RIAÑO", firstName: "DAVID", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "MÉNDEZ PEÑA", firstName: "LUCIANA", exam: "YLE Flyers", year: "2024", score: "RW2-L2-S5" }, 
    { lastName: "PAEZ PINEDA", firstName: "LUIS FELIPE", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "PEREZ MONTENEGRO", firstName: "JUAN DAVID", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "RUÍZ MANRIQUE", firstName: "LEYLA ISABELLA", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "TRUJILLO ESPITALETA", firstName: "JULIANA", exam: "YLE Flyers", year: "2024", score: "RW1-L2-S3" }, 
    { lastName: "VASCO VEGA", firstName: "JUAN SEBASTIAN", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "VERDUGO DE LA VEGA", firstName: "JUAN DIEGO", exam: "YLE Flyers", year: "2024", score: "RW2-L2-S4" }, 
    { lastName: "VIVAS MOLINA", firstName: "MARIA FERNANDA", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "GUERRA ALVAREZ", firstName: "MARIA GABRIELA", exam: "YLE Flyers", year: "2024", score: "RW2-L3-S5" }, 
    { lastName: "RUEDA OSORIO", firstName: "JUAN MARTÍN", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "ALVIRA GACHARNA", firstName: "NICOLAS", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "AVENDAÑO BARÓN", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "BOHÓRQUEZ CARRANZA", firstName: "JERÓNIMO JACOBO", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "BONILLA URUEÑA", firstName: "MARIANA", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S4" }, 
    { lastName: "CAMACHO PINILLA", firstName: "MATHIAS", exam: "YLE Flyers", year: "2024", score: "RW2-L5-S5" }, 
    { lastName: "CASTILLO BOTÓN", firstName: "JUAN MARTÍN", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CRUZ VELASQUEZ", firstName: "SARA", exam: "YLE Flyers", year: "2024", score: "Pending" }, 
    { lastName: "FORIGUA BARRERA", firstName: "MARÍA ALEJANDRA", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "GALVIS RUBIO", firstName: "ESTEBAN", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S4" }, 
    { lastName: "GUERRA URIBE", firstName: "LIAN MARTIN", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "HERNÁNDEZ ESPITIA", firstName: "JUAN JOSÉ", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "HERREÑO RODRÍGUEZ", firstName: "SAMANTHA", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S5" }, 
    { lastName: "JIMÉNEZ ESPINOSA", firstName: "MARÍA ALEJANDRA", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S4" }, 
    { lastName: "LANCHEROS ÁNGEL", firstName: "ANA MARÍA", exam: "YLE Flyers", year: "2024", score: "RW2-L3-S5" }, 
    { lastName: "MARÍN CABEZAS", firstName: "PAULO CÉSAR", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "MUÑOZ GUARNIZO", firstName: "GIBRAN ARLEY", exam: "YLE Flyers", year: "2024", score: "RW1-L4-S5" }, 
    { lastName: "NIETO GUERRERO", firstName: "LUIS ANTOΝΙΟ", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "SERRANO JAIME", firstName: "DANIEL FELIPE", exam: "YLE Flyers", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "UGARTE CELY", firstName: "MARÍA JOSÉ", exam: "YLE Flyers", year: "2024", score: "RW4-L3-S5" }, 
    { lastName: "VARGAS BELTRÁN", firstName: "MARÍA LUCÍA", exam: "YLE Flyers", year: "2024", score: "RW3-L3-S5" }, 
    { lastName: "VERA SOLANO", firstName: "MARÍA VICTORIA", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "RUIZ ARANA", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2024", score: "RW3-L4-S5" }, 
    { lastName: "ALEJO CALDERON", firstName: "ARQUIMEDES ARTURO", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "BERMÚDEZ SANABRIA", firstName: "DAVID RICARDO", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "BOTÓN PABÓN", firstName: "SIMÓN MAURICIO", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "CIFUENTES YEPES", firstName: "JULIANA LUCÍA", exam: "YLE Flyers", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "ECHEVERRIA MEDRAΝΟ", firstName: "EMILIANO", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S5" }, 
    { lastName: "FRANCO MUÑOZ", firstName: "GEORGE DYLAN", exam: "YLE Flyers", year: "2024", score: "RW1-L4-S5" }, 
    { lastName: "GAVIRIA ORJUELA", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2024", score: "RW1-L4-S4" }, 
    { lastName: "GONZÁLEZ VILLEROS", firstName: "MARÍA VICTORIA", exam: "YLE Flyers", year: "2024", score: "RW5-L4-S5" }, 
    { lastName: "HIGUERA LÓPEZ", firstName: "SARA ISABELLA", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "JIMENEZ MARTINEZ", firstName: "LUNA ISABELLA", exam: "YLE Flyers", year: "2024", score: "RW2-L5-S4" }, 
    { lastName: "LOAIZA PIΝΤΟ", firstName: "IVÁN DAVID", exam: "YLE Flyers", year: "2024", score: "RW4-L5-S4" }, 
    { lastName: "LÓPEZ VILLAMIL", firstName: "SAMUEL ALEJANDRO", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "OJEDA FUENTES", firstName: "EMILY GABRIELA", exam: "YLE Flyers", year: "2024", score: "RW4-L3-S5" }, 
    { lastName: "OÑATE MOGOLLÓN", firstName: "JUAN JOSÉ", exam: "YLE Flyers", year: "2024", score: "RW1-L4-S5" }, 
    { lastName: "PIÑEROS DURAN", firstName: "ISABELA", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "ROJAS CRUZ", firstName: "MARÍA CAMILA", exam: "YLE Flyers", year: "2024", score: "RW4-L3-S5" }, 
    { lastName: "SÁNCHEZ GONZÁLEZ", firstName: "MARIA PAULA", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S4" }, 
    { lastName: "SUESCÚN MORENO", firstName: "JUAN PABLO", exam: "YLE Flyers", year: "2024", score: "RW2-L4-S4" }, 
    { lastName: "TABARES MONCADA", firstName: "MARIA JOSE", exam: "YLE Flyers", year: "2024", score: "RW3-L3-S5" }, 
    { lastName: "VARGAS ROMERO", firstName: "DIEGO ALEJANDRO", exam: "YLE Flyers", year: "2024", score: "RW3-L5-S5" }, 
    { lastName: "ZAPATA ÁLVAREZ", firstName: "MIGUEL ÁNGEL", exam: "YLE Flyers", year: "2024", score: "RW4-L4-S5" }, 
    { lastName: "COBOS GARCIA", firstName: "EMILIO JOSE", exam: "YLE Flyers", year: "2024", score: "RW3-L3-S5" }, 
    { lastName: "LIZARAZO TORRES", firstName: "MARIA JULIANA", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    { lastName: "PINILLA RUIZ", firstName: "ESTEBAN", exam: "YLE Flyers", year: "2024", score: "RW5-L5-S5" }, 
    
     // Data from ResultsSummary_YLE_Flyers_04_SEPTEMBER_2025.pdf
    { lastName: "ANGULO VELASCO", firstName: "SILVANA", exam: "YLE Flyers", year: "2025", score: "RW1-L2-S3" }, 
    { lastName: "ARIZA CORREDOR", firstName: "DANNA SOFIA", exam: "YLE Flyers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "AROCHA LATORRE", firstName: "TOMAS", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "AVILA MARTINEZ", firstName: "ISABEL GABRIELA", exam: "YLE Flyers", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "BARON GUTIERREZ", firstName: "JUANA ISABELLA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "BLANCO LOPEZ", firstName: "MIGUEL ANGEL", exam: "YLE Flyers", year: "2025", score: "RW2-L1-S4" }, 
    { lastName: "BUSTAMANTE CELIS", firstName: "VERONICA", exam: "YLE Flyers", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "BUSTAMANTE RODRIGUEZ", firstName: "ALEJANDRA SOFIA", exam: "YLE Flyers", year: "2025", score: "RW2-L4-S4" }, 
    { lastName: "CARDONA VILLARRUEL", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S4" }, 
    { lastName: "CARRERA GONZALEZ", firstName: "SOFIA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S4" }, 
    { lastName: "CARVAJAL GARCIA", firstName: "ΜΙΑ", exam: "YLE Flyers", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "CASTRO CONTRERAS", firstName: "JUAN DIEGO", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "CUELLAR MARTINEZ", firstName: "CAMILA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "DIAZ HERNANDEZ", firstName: "SAMUEL FELIPE", exam: "YLE Flyers", year: "2025", score: "Pending" }, 
    { lastName: "DURAN GOMEZ", firstName: "ANA VICTORIA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "GOMEZ GALLEGO", firstName: "JOHAN MATIAS", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "LEAL TARAZONA", firstName: "ANA MARIA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "OBISPO HOYOS", firstName: "ISABELLA", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "PACHECO VEGA", firstName: "VALERIA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "PARRADO GARCIA", firstName: "CHRISTIAN SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW1-L4-S5" }, 
    { lastName: "PEDRAZA SANCHEZ", firstName: "JUANITA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "PINEDA QUINAYAS", firstName: "JUAN SEBASTIAN", exam: "YLE Flyers", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "PINZON ARIZA", firstName: "MATEO", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "PUYO GONZALEZ", firstName: "NICOLAS", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "RAMIREZ JIMENEZ", firstName: "MARTIN", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "RIOS ARANGUREN", firstName: "GABRIEL SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "TRIANA REYES", firstName: "MARIA ANTΟΝΙΑ", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "BARBOSA LAVERDE", firstName: "IKER", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "BAYONA BAYONA", firstName: "MARIANA", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "BERNAL TAMAYO", firstName: "SILVANA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "BLANCO JULIO", firstName: "MARIANA DEL CARMEN", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "BLANCO PARRA", firstName: "JOSE ALEJANDRO", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "DIAZ MOLINA", firstName: "VALERIA", exam: "YLE Flyers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "DUQUE SATIZABAL", firstName: "GERONIMO", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "FERNANDEZ MENA", firstName: "LUCAS DANIEL", exam: "YLE Flyers", year: "2025", score: "RW4-L3-S5" }, 
    { lastName: "GALVIS ROSERO", firstName: "JUAN DAVID", exam: "YLE Flyers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "GARAVITO PINTO", firstName: "DANNA SOFIA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "GARCIA CAMARGO", firstName: "JUAN ANDRES", exam: "YLE Flyers", year: "2025", score: "RW5-L3-S5" }, 
    { lastName: "GOMEZ LOPEZ", firstName: "MARIANA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "HERRERA MOTTA", firstName: "DANIEL SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S4" }, 
    { lastName: "MARIÑO FUENTES", firstName: "MARIA ALEJANDRA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "MELO MALAVER", firstName: "DANIEL ESTEBAN", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "MENDEZ BONILLA", firstName: "JUAN JOSE", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "NEIRA FARFAN", firstName: "ANA VALERIA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "OLARTE GIRALDO", firstName: "ANDRES", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "RAMIREZ SALAZAR", firstName: "ALEJANDRO", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "RAMOS PARRA", firstName: "MARIA JULIANA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "RODRIGUEZ GIRALDO", firstName: "MARIA PAULA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "RODRIGUEZ SARMIENTO", firstName: "MARTINA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "SANCHEZ MONTENEGRO", firstName: "ISABELLA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "SEGOVIA MUÑOZ", firstName: "SARA VALENTINA", exam: "YLE Flyers", year: "2025", score: "RW3-L3-S5" }, 
    { lastName: "TAMAYO CHAPARRO", firstName: "VERONICA", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "TELLO ORTIZ", firstName: "LIBIA SOFIA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "TORRES DEVIA", firstName: "ANDREY FELIPE", exam: "YLE Flyers", year: "2025", score: "RW2-L4-S5" }, 
    { lastName: "VELEZ NIÑO", firstName: "JUAN ANGEL", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "ARCINIEGAS", firstName: "MAXIMILIANO", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "BARROS CASTRO", firstName: "SARA ISABEL", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "BERNAL TAMAYO", firstName: "LETICIA", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "BLANCO PARRA", firstName: "JUAN DIEGO", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "BOHORQUEZ PESCADOR", firstName: "ALISON DANIELA", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "CARDOZO NIÑO", firstName: "ALVARO", exam: "YLE Flyers", year: "2025", score: "RW1-L3-S5" }, 
    { lastName: "CASTRO DELGADO", firstName: "JUAN EMILIO", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "CORREDOR BARRIGA", firstName: "VALERIA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "CUADRADO SAMBONI", firstName: "SALOME", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "CUADRADO SUAREZ", firstName: "DULCE MARIA", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "DAVID FERRUCHO", firstName: "IVAN SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW4-L4-S5" }, 
    { lastName: "ECHEVERRIA CASAS", firstName: "THOMAS SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW1-L3-S4" }, 
    { lastName: "GARCIA FRESNEDA", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "GOMEZ CARRASCAL", firstName: "JUAN JOSE", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "GROSSO PRIETO", firstName: "JACOBO", exam: "YLE Flyers", year: "2025", score: "RW5-L4-S5" }, 
    { lastName: "GUAMAN LANCHEROS", firstName: "MARIA JULIANA", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "LARA PINEDA", firstName: "MARTIN", exam: "YLE Flyers", year: "2025", score: "RW3-L5-S5" }, 
    { lastName: "NIÑO HERNANDEZ", firstName: "ASHLEY JULIETH", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "ORTIZ VALENTIN", firstName: "MARIA PAULA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "PIEDRAHITA JUTINICO", firstName: "GABRIELA", exam: "YLE Flyers", year: "2025", score: "RW4-L3-S5" }, 
    { lastName: "PINO TOLOZA", firstName: "ISABELLA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    { lastName: "PINZON RAMIREZ", firstName: "JUAN ESTEBAN", exam: "YLE Flyers", year: "2025", score: "RW4-L5-S5" }, 
    { lastName: "RIAÑO PABLOS", firstName: "MATIAS", exam: "YLE Flyers", year: "2025", score: "RW2-L1-S4" }, 
    { lastName: "RINCON CAMACHO", firstName: "SALOME", exam: "YLE Flyers", year: "2025", score: "RW5-L3-S5" }, 
    { lastName: "RODRIGUEZ MORENO", firstName: "ALEJANDRO", exam: "YLE Flyers", year: "2025", score: "RW3-L4-S5" }, 
    { lastName: "VARGAS OJEDA", firstName: "SANTIAGO", exam: "YLE Flyers", year: "2025", score: "RW2-L3-S5" }, 
    { lastName: "VILLABONA RINCON", firstName: "SARA", exam: "YLE Flyers", year: "2025", score: "RW5-L5-S5" }, 
    
  

   
];